### ISSUE TITLE
Can't make it work properly

### ISSUE THREAD

**Issue by assislucas** [chesleybrown/bitbucket-codeship-status#6]
Hi, I'm trying to make the app work.
First try I created an OAuth key on Bitbucket and set on my app the OAuth key as the BITBUCKET_PASSWORD. 
After I tried setting BITBUCKET_PASSWORD to my bitbucket password which also didn't work.

In both cases I see on my app that "Access to Bitbucket was denied."

Any clues on how to fix this?

**Comment by chesleybrown** [comment]
Did you set the BITBUCKET_USERNAME?

It has to be your username and I believe it was to be all lowercase as well. 

Cheers,
Ches

—
Chesley Brown
chesleybrown.ca
St. John's, NL
C: (709) 697-5407

**Comment by assislucas** [comment]
Yes I set it to my bitbucket username.
Is there an manual api call I can make to check if Bitbucket is allowing my
access?

--
Lucas Amaral

**Comment by assislucas** [comment]
I should add this "key" (on the screenshot) as the BITBUCKET_PASSWORD right? And my username as the BITBUCKET_USERNAME.
![selection_039](https://cloud.githubusercontent.com/assets/10120697/7693738/318bb99c-fd8b-11e4-8c44-dc3905a69b11.png)

**Comment by chesleybrown** [comment]
Oh. It doesn't use OAuth keys. 

The option under OAuth in the menu called "API key" is what you need to use. The username is just your username or your organization name in all lowercase. Then the password is just the API key in that section. 

Hope that helps,
Ches

—
Chesley Brown
chesleybrown.ca
St. John's, NL
C: (709) 697-5407

**Comment by assislucas** [comment]
Thanks, now app has access to bitbucket. But I create a pull request it
still doesn't work.
I see this on the server logs:

2015-05-19T17:53:16.855523+00:00 heroku[router]: at=info method=POST
path="/pull-request/9512b6a0-d810-0132-1b9c-56577b4e3777/78832" host=
shippo-bitbucket-codeship.herokuapp.com
request_id=a8bdcf97-dffa-4a8e-9c90-286762fd9da7 fwd="131.103.20.165"
dyno=web.1 connect=3ms service=29ms status=400 bytes=140

Any clues of what might be happening?

Thanks!

--
Lucas Amaral

**Comment by timurkhafizov** [comment]
Same situation here.
I tried to use team login and API key as ENV vars and in hook URL - app responds with 400.
I tried to use team's admin login and password - same.

Maybe it is related with Bitbucket's policy for team logins - they do not allow to login with team login.

**Comment by timurkhafizov** [comment]
We have debugged application a bit and it seems that on pull request update there is no key `pullrequest_created`.
Line 38 in `app.js` checks this key and returns 400 if this key is missing.

We've got this request body from BitBucket:
```javascript
{ pullrequest_updated:  
  { description: '', 
       title: 'Static content of main page', 
       destination: { commit: [Object], branch: [Object], repository: [Object] }, 
       reason: '', 
       source: { commit: [Object], branch: [Object], repository: [Object] }, 
       state: 'OPEN', 
       author:  
        { username: 'timurkhafizov', 
          display_name: 'Timur Khafizov', 
          uuid: '{MY_UUID}', 
          links: [Object] }, 
       date: '2015-05-20T07:49:08.468970+00:00' } }
```

Line 45 in `app.js` check for pull request id which is missing in current request body. So app will not be able to update PR then even if we pass line 38 check.

Did BitBucket change Pull Request POST hook request format?

**Comment by chesleybrown** [comment]
Current the app only adds the code ship status on initial pull request creation. It won't do anything on a pull request update. This might be something I'll look into improving in the future (or you're welcome to submit a pull request).

But for now, can you try creating a new pull request and see if it works?

Ches

—
Chesley Brown
chesleybrown.ca
St. John's, NL
C: (709) 697-5407

**Comment by chesleybrown** [comment]
Possibly helpful: Another github user has forked my project and converted it to use OAUTH.

https://github.com/vincentkwok/bitbucket-codeship-status

I have not tested this however. Would be nice to one day get that merged into this project so that it supports both.
